name: Github Actions Example hm

on:
  pull_request:
  push:
    branches: 
      - master
      - develop

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: samdd
        delete-branch: true
        token: ${{ secrets.GITHUB_TOKEN }}
