name: Github Actions Example hm

on:
  pull_request:
  push:
    branches: 
      - master

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: sass
        delete-branch: true
        token: ${{ secrets.GITHUB_TOKEN }}
