name: Github Actions Example

on:
  pull_request:
  push:
    branches: 
      - master
      - develop

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
	token: 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
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
	token: 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
