name: Example

on:
   push:

jobs:
  test:
        name: testing
	runs-on: ubuntu-latest
        steps: 
  	 -uses: actions/checkout@v3
         -name: Create Pull Request
          uses:peter-evans/create-pull-request@v4
